version: "3.8"

services:
  starterproddb:
    image: bitnami/mysql:8.1.0
    container_name: starterproddb
    restart: always
    env_file:
      - .env.db.docker
    volumes:
      - softyshop-db:/bitnami/mysql/data
      - ./initdb/dump.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306"]
      interval: 10s
      timeout: 5s
      retries: 3
  starterprodapi:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    container_name: starterprodapi
    restart: always
    volumes:
      - ../../public:/app/public
    env_file:
      - .env.server.docker
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:3306/v1/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      starterproddb:
        condition: service_healthy
    links:
      - starterproddb
  starterprodadminer:
    container_name: starterprodadminer
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
volumes:
  mysqlstarterprod-data:
