version: '3.8'
services:
  starterproddb:
    image: mysql:8.1.0
    container_name: starterproddb
    restart: always
    env_file:
      - .env.db.docker
    volumes:
      - ../../initdb/:/docker-entrypoint-initdb.d
      - mariadbstarterprod-data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  starterprodapi:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    container_name: starterprodapi
    restart: always
    volumes:
      - ../../public:/app/public
    env_file:
      - .env.server.docker
    ports:
      - '6001:6001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:6001/v1/api/healthcheck']
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      starterproddb:
        condition: service_healthy
    links:
      - starterproddb
  starterprodadminer:
    container_name: starterprodadminer
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
volumes:
  mariadbstarterprod-data:
